=== winitsky/JavaEE/internetbank.dao/src/test/java/resources/dbxsd/dataset.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" xmlns:dflt="ibank_test">
	<xsd:import namespace="ibank_test" schemaLocation="ibank_test.xsd" />
	<xsd:element name="dataset">
		<xsd:complexType>
			<xsd:choice minOccurs="0" maxOccurs="unbounded">
				<xsd:element name="users" type="dflt:users__type" />
				<xsd:element name="accounts" type="dflt:accounts__type" />
				<xsd:element name="archive" type="dflt:archive__type" />
				<xsd:element name="operations" type="dflt:operations__type" />
				<xsd:element name="role" type="dflt:role__type" />
				<xsd:any namespace="ibank_test" />
			</xsd:choice>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== winitsky/JavaEE/internetbank.dao/src/test/java/resources/InternetBankDaoImplTest.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="resources/dbxsd/dataset.xsd">
         
  <users id="1" login="petrov@mail.ru" password="123"  surname="Petrov" name="Petr"/>
  <users id="2" login="ivanov@mail.ru" password="123" surname="Ivanov" name="Ivan"/>
  <users id="3" login="sidirov@tut.by" password="123"  surname="Sidorov" name="Sidor"/>
  
  
  <accounts account="123456789" user_id="1" balance="50000" />
  <accounts account="987654321" user_id="2" balance="4995000" />
  <accounts account="321654987" user_id="3" balance="2800000" />
  
  <archive id="1" user_id="2" operation_id="2" sum="20000" date="2015-08-04"/>
  <archive id="2" user_id="1" operation_id="1" sum="10000" date="2015-08-14"/>
  <archive id="3" user_id="3" operation_id="4" sum="30000" date="2015-08-10"/>
  
  <operations id="1" name="Payment for phone" account="12312312" type="2"/>
  <operations id="2" name="Payment for internet" account="77712312" type="2"/>
  <operations id="4" name="International payment" account="32112314" type="1"/>
 
  
  <role id="1" user_id="1" role="2"/>
  <role id="2" user_id="2" role="2"/>
  <role id="3" user_id="3" role="1"/>

</dataset>
